### ISSUE TITLE
settings.json not found

### ISSUE THREAD

**Issue by SpiritGun91** [hxAri/ILAPIs#4]
![Screenshot_20230703-201943_crDroid Home](https://github.com/hxAri/Kanashi/assets/101740573/fd5d087f-fb7f-47cc-84c6-501d10eae460)
I can "touch settings.json" to fix that error, but I don't know what to write in settings.json after, which causes another error. Could you provide an example? Thanks!

**Comment by hxAri** [comment]
> ![Screenshot_20230703-201943_crDroid Home](https://user-images.githubusercontent.com/101740573/250695407-fd5d087f-fb7f-47cc-84c6-501d10eae460.png) I can "touch settings.json" to fix that error, but I don't know what to write in settings.json after, which causes another error. Could you provide an example? Thanks!

Type Enter or press Y/y then Enter it will automatically create a new `settings.json` file

**Comment by hxAri** [comment]
Type Enter or press Y/y then Enter it will automatically create a new `settings.json` file in current working directory.

And don't forget not to share the file with anyone, your login information will be stored there so you can use it again in the future
