### ISSUE TITLE
Hashing algorithm

### ISSUE THREAD

**Issue by 922tech** [hxAri/ILAPIs#5]
It made me curious how you figured out what encrypting algorithm Instagram uses to generate the 'enc_password' in the login page front-end. How really?

**Comment by hxAri** [comment]
> It made me curious how you figured out what encrypting algorithm Instagram uses to generate the 'enc_password' in the login page front-end. How really?

Thanks bro, I just made the program to be as similar as possible to how Instagram Web works, and the reason why I can tell is I'm doing a clone of what Instagram does when I send a request, and to find out you can monitor it with the Developer Tool in your favorite browser, and try to enter the wrong password, and see the payload of the request it made, i hope this help you :)
