### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by wydadi01** [hxAri/ILAPIs#6]
How can i send password reset request using this api

**Comment by hxAri** [comment]
Hi, @wroga, thank you for opening the issue, currently [Kanashī](https://github.com/hxAri/Kanashi) does not provide this API, maybe a future feature if possible, currently I am focusing on guessing the v10 password encryption algorithm used by Instagram to avoid checkpoints when logging in and by some other busy work, thank you for stopping by [Kanashī](https://github.com/hxAri/Kanashi).
